
package coko.artefacts.x.ege.services._1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "BiException", targetNamespace = "urn://x-artefacts-coko/ege/services/exceptions/1.0.0")
public class BiException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private coko.artefacts.x.ege.services.exceptions._1_0.BiException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public BiException(String message, coko.artefacts.x.ege.services.exceptions._1_0.BiException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public BiException(String message, coko.artefacts.x.ege.services.exceptions._1_0.BiException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: coko.artefacts.x.ege.services.exceptions._1_0.BiException
     */
    public coko.artefacts.x.ege.services.exceptions._1_0.BiException getFaultInfo() {
        return faultInfo;
    }

}
