
package coko.artefacts.x.ege.services._1_0;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EventService", targetNamespace = "urn://x-artefacts-coko/ege/services/1.0.0", wsdlLocation = "http://192.168.1.77:9082/?wsdl")
public class EventService
    extends Service
{

    private final static URL EVENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException EVENTSERVICE_EXCEPTION;
    private final static QName EVENTSERVICE_QNAME = new QName("urn://x-artefacts-coko/ege/services/1.0.0", "EventService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.77:9082/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EVENTSERVICE_WSDL_LOCATION = url;
        EVENTSERVICE_EXCEPTION = e;
    }

    public EventService() {
        super(__getWsdlLocation(), EVENTSERVICE_QNAME);
    }

    public EventService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EVENTSERVICE_QNAME, features);
    }

    public EventService(URL wsdlLocation) {
        super(wsdlLocation, EVENTSERVICE_QNAME);
    }

    public EventService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EVENTSERVICE_QNAME, features);
    }

    public EventService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EventService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EventServicePort
     */
    @WebEndpoint(name = "eventServicePort")
    public EventServicePort getEventServicePort() {
        return super.getPort(new QName("urn://x-artefacts-coko/ege/services/1.0.0", "eventServicePort"), EventServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EventServicePort
     */
    @WebEndpoint(name = "eventServicePort")
    public EventServicePort getEventServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("urn://x-artefacts-coko/ege/services/1.0.0", "eventServicePort"), EventServicePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EVENTSERVICE_EXCEPTION!= null) {
            throw EVENTSERVICE_EXCEPTION;
        }
        return EVENTSERVICE_WSDL_LOCATION;
    }

}
