
package coko.artefacts.x.ege.services._1_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "eventServicePort", targetNamespace = "urn://x-artefacts-coko/ege/services/1.0.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    coko.artefacts.x.ege.services._1_0.ObjectFactory.class,
    coko.artefacts.x.ege.services.exceptions._1_0.ObjectFactory.class
})
public interface EventServicePort {


    /**
     * 
     * @param newRequest
     * @return
     *     returns coko.artefacts.x.ege.services._1_0.NewResponseType
     * @throws BiException
     */
    @WebMethod(action = "urn://nahodka.ru/services/eventService/manageRequest")
    @WebResult(name = "NewResponse", targetNamespace = "urn://x-artefacts-coko/ege/services/1.0.0", partName = "NewResponse")
    public NewResponseType manageRequest(
        @WebParam(name = "NewRequest", targetNamespace = "urn://x-artefacts-coko/ege/services/1.0.0", partName = "NewRequest")
        NewRequestType newRequest)
        throws BiException
    ;

}
